# This file intentionally left blank

BOARD = BLACKPILL_STM32_F411

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
#RGB_MATRIX_CUSTOM_USER = yes

#WS2812_DRIVER = pwm

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

EEPROM_DRIVER = i2c
