# This file intentionally left blank

#BACKLIGHT_ENABLE = yes

#RGBLIGHT_ENABLE = yes
#RGBLIGHT_DRIVER = WS2812

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
#RGB_MATRIX_CUSTOM_USER = yes

#WS2812_DRIVER = pwm

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

EEPROM_DRIVER = i2c
